environment:  #секция, где определяются переменные окружения для сборки
  nodejs_version: "22" # самая последняя стабильная версия

branches: # какие ветки git отслеживаются
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование, чтобы node_modules работал быстрее

install:
  - npm install  # команда установки зависимостей, указанных в файле package.json

build_script: #секция, в которой указаны команды для сборки проекта
  - npm run build   # команда сборки из файла package.json

test_script: #секция, в которой указаны команды для тестирования проекта
  - npm run lint # скрипт тестирования

deploy_script:
  - git config --global user.email "your-email@example.com"
  - git config --global user.name "Your Name"
  - git checkout -b gh-pages
  - git --work-tree public add --all
  - git --git-dir public/.git commit -m "Deploy to GitHub Pages"
  - git subtree push --prefix public origin gh-pages
